import './globals.css';
import { Inter } from 'next/font/google';
import Nav from '@/components/nav/Nav';
import BottomNav from '@/components/nav/BottomNav';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body className={`space-y-4 ${inter.className}`}>
        <Nav />
        {children}
        <BottomNav/>
      </body>
    </html>
  );
}
